version: "3.2"
services:
  lambda:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    environment:
      DGRAPHQL_URL: http://alpha:8080
      DQL_URL: alpha:9080
    ports: 
      - 8686:8686
    volumes:
      - .:/lambda
    networks:
      - dgraph

networks:
  dgraph:
    external: true