version: "3.2"
services:
  lambda:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    environment:
      DGRAPH_URL: http://alpha:8080
    ports: 
      - 8686:8686
    volumes:
      - .:/lambda